services:
  pulse-hub:
    image: pulse-hub:1.0.5
    container_name: pulse-hub
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:8090"
    volumes:
      - ../../../pulse_data:/pulse_data
    command: ["serve", "--dir=/pulse_data", "--http=0.0.0.0:8090"]


