const ASSET_IMPORT_TEMPLATE_ROWS: Record<string, string>[] = [
	{
		name: "联通千兆宽带",
		type: "internet",
		status: "active",
		location: "弱电箱",
		vendor: "联通",
		model: "千兆宽带",
		serial_number: "",
		management_ip: "",
		role: "主宽带入口",
		notes: "公网入口作为资产维护，可在网络拓扑里手动连接到路由器。",
		parent_asset: "",
		"metadata.fixed_ipv4": "",
		"metadata.fixed_ipv6": "",
		"metadata.mac": "",
		"metadata.management_url": "",
		"metadata.support_url": "",
		"metadata.product_url": "",
		"metadata.official_url": "",
		"metadata.down_mbps": "1000",
		"metadata.up_mbps": "100",
		"metadata.public_ipv4": "",
		"metadata.public_ipv6": "",
		"metadata.has_public_ip": "yes",
		"metadata.port_count": "",
		"metadata.default_port_speed_mbps": "",
		"metadata.wifi_standard": "",
		"metadata.ssid_note": "",
		"metadata.cpu_model": "",
		"metadata.cpu_vendor": "",
		"metadata.cpu_support_url": "",
		"metadata.memory_gb": "",
		"metadata.storage_summary": "",
		"metadata.primary_nic_speed_mbps": "",
		"metadata.motherboard_vendor": "",
		"metadata.motherboard_model": "",
		"metadata.motherboard_support_url": "",
		"metadata.bios_vendor": "",
		"metadata.gpu_detail": "",
		"metadata.gpu_vendor": "",
		"metadata.gpu_model": "",
		"metadata.gpu_board_vendor": "",
		"metadata.gpu_support_url": "",
		"metadata.gpu_vram_gb": "",
		"metadata.memory_detail": "",
		"metadata.memory_vendor": "",
		"metadata.memory_model": "",
		"metadata.memory_type": "",
		"metadata.memory_speed_mhz": "",
		"metadata.memory_slots_summary": "",
		"metadata.memory_support_url": "",
		"metadata.storage_detail": "",
		"metadata.storage_vendor": "",
		"metadata.storage_model": "",
		"metadata.storage_media": "",
		"metadata.storage_serial_note": "",
		"metadata.storage_support_url": "",
		"metadata.nic_detail": "",
		"metadata.nic_vendor": "",
		"metadata.nic_model": "",
		"metadata.wifi_vendor": "",
		"metadata.wifi_model": "",
		"metadata.nic_support_url": "",
		"metadata.wifi_support_url": "",
		"metadata.chassis_power_detail": "",
		"metadata.chassis_vendor": "",
		"metadata.chassis_model": "",
		"metadata.chassis_support_url": "",
		"metadata.psu_vendor": "",
		"metadata.psu_model": "",
		"metadata.psu_support_url": "",
		"metadata.hardware_fingerprint_note": "",
		"metadata.hardware_match_note": "",
		"metadata.planned_agent": "",
		"metadata.connection_type": "",
		"metadata.power_mode": "",
		"metadata.protocol": "",
		"metadata.entity_id": "",
		"metadata.gateway_name": "",
		"metadata.internal_url": "",
		"metadata.external_url": "",
		"metadata.purchase_date": "",
		"metadata.online_date": "",
		"metadata.warranty_until": "",
		"metadata.owner": "",
	},
	{
		name: "V271-20",
		type: "router",
		status: "active",
		location: "弱电箱",
		vendor: "联通",
		model: "V271-20",
		serial_number: "",
		management_ip: "192.168.1.1",
		role: "网关 / 路由 / DHCP / Wi-Fi AP",
		notes: "",
		parent_asset: "",
		"metadata.fixed_ipv4": "192.168.1.1",
		"metadata.fixed_ipv6": "",
		"metadata.mac": "",
		"metadata.management_url": "http://192.168.1.1",
		"metadata.support_url": "",
		"metadata.product_url": "",
		"metadata.official_url": "",
		"metadata.down_mbps": "",
		"metadata.up_mbps": "",
		"metadata.public_ipv4": "",
		"metadata.public_ipv6": "",
		"metadata.has_public_ip": "",
		"metadata.port_count": "4",
		"metadata.default_port_speed_mbps": "1000",
		"metadata.wifi_standard": "Wi-Fi 6",
		"metadata.ssid_note": "主 Wi-Fi / IoT Wi-Fi",
		"metadata.cpu_model": "",
		"metadata.memory_gb": "",
		"metadata.storage_summary": "",
		"metadata.primary_nic_speed_mbps": "",
		"metadata.motherboard_vendor": "",
		"metadata.motherboard_model": "",
		"metadata.gpu_detail": "",
		"metadata.memory_detail": "DDR4 32GB",
		"metadata.storage_detail": "系统盘 + 数据盘",
		"metadata.storage_media": "NVMe / SATA",
		"metadata.nic_detail": "2.5G 物理网卡",
		"metadata.nic_model": "按实际芯片填写",
		"metadata.chassis_power_detail": "",
		"metadata.planned_agent": "",
		"metadata.connection_type": "",
		"metadata.power_mode": "AC",
		"metadata.protocol": "",
		"metadata.entity_id": "",
		"metadata.gateway_name": "",
		"metadata.internal_url": "",
		"metadata.external_url": "",
		"metadata.purchase_date": "",
		"metadata.online_date": "",
		"metadata.warranty_until": "",
		"metadata.owner": "",
	},
	{
		name: "CM754",
		type: "switch",
		status: "active",
		location: "弱电箱",
		vendor: "",
		model: "CM754",
		serial_number: "",
		management_ip: "",
		role: "2.5G 交换机",
		notes: "无 IPv4 的交换机也可以作为手动资产维护。",
		parent_asset: "",
		"metadata.fixed_ipv4": "",
		"metadata.fixed_ipv6": "",
		"metadata.mac": "",
		"metadata.management_url": "",
		"metadata.support_url": "",
		"metadata.product_url": "",
		"metadata.official_url": "",
		"metadata.down_mbps": "",
		"metadata.up_mbps": "",
		"metadata.public_ipv4": "",
		"metadata.public_ipv6": "",
		"metadata.has_public_ip": "",
		"metadata.port_count": "5",
		"metadata.default_port_speed_mbps": "2500",
		"metadata.wifi_standard": "",
		"metadata.ssid_note": "",
		"metadata.cpu_model": "",
		"metadata.memory_gb": "",
		"metadata.storage_summary": "",
		"metadata.primary_nic_speed_mbps": "",
		"metadata.motherboard_vendor": "",
		"metadata.motherboard_model": "",
		"metadata.gpu_detail": "",
		"metadata.memory_detail": "",
		"metadata.storage_detail": "",
		"metadata.nic_detail": "",
		"metadata.chassis_power_detail": "",
		"metadata.planned_agent": "",
		"metadata.connection_type": "",
		"metadata.power_mode": "AC",
		"metadata.protocol": "",
		"metadata.entity_id": "",
		"metadata.gateway_name": "",
		"metadata.internal_url": "",
		"metadata.external_url": "",
		"metadata.purchase_date": "",
		"metadata.online_date": "",
		"metadata.warranty_until": "",
		"metadata.owner": "",
	},
	{
		name: "飞牛 NAS",
		type: "nas",
		status: "active",
		location: "书房",
		vendor: "自组",
		model: "fnOS",
		serial_number: "",
		management_ip: "192.168.1.30",
		role: "存储 / Docker 宿主",
		notes: "",
		parent_asset: "",
		"metadata.fixed_ipv4": "192.168.1.30",
		"metadata.fixed_ipv6": "",
		"metadata.mac": "",
		"metadata.management_url": "http://192.168.1.30",
		"metadata.support_url": "",
		"metadata.product_url": "",
		"metadata.official_url": "",
		"metadata.down_mbps": "",
		"metadata.up_mbps": "",
		"metadata.public_ipv4": "",
		"metadata.public_ipv6": "",
		"metadata.has_public_ip": "",
		"metadata.port_count": "",
		"metadata.default_port_speed_mbps": "",
		"metadata.wifi_standard": "",
		"metadata.ssid_note": "",
		"metadata.cpu_model": "",
		"metadata.memory_gb": "32",
		"metadata.storage_summary": "系统盘 + 数据盘",
		"metadata.primary_nic_speed_mbps": "2500",
		"metadata.motherboard_vendor": "",
		"metadata.motherboard_model": "",
		"metadata.gpu_detail": "",
		"metadata.memory_detail": "",
		"metadata.storage_detail": "",
		"metadata.nic_detail": "",
		"metadata.chassis_power_detail": "",
		"metadata.planned_agent": "yes",
		"metadata.connection_type": "ethernet",
		"metadata.power_mode": "AC",
		"metadata.protocol": "",
		"metadata.entity_id": "",
		"metadata.gateway_name": "",
		"metadata.internal_url": "",
		"metadata.external_url": "",
		"metadata.purchase_date": "",
		"metadata.online_date": "",
		"metadata.warranty_until": "",
		"metadata.owner": "",
	},
	{
		name: "Pulse 控制台",
		type: "web_endpoint",
		status: "active",
		location: "内网服务",
		vendor: "自建",
		model: "Pulse",
		serial_number: "",
		management_ip: "",
		role: "资产与监控入口",
		notes: "",
		parent_asset: "飞牛 NAS",
		"metadata.fixed_ipv4": "",
		"metadata.fixed_ipv6": "",
		"metadata.mac": "",
		"metadata.management_url": "",
		"metadata.support_url": "",
		"metadata.product_url": "",
		"metadata.official_url": "",
		"metadata.down_mbps": "",
		"metadata.up_mbps": "",
		"metadata.public_ipv4": "",
		"metadata.public_ipv6": "",
		"metadata.has_public_ip": "",
		"metadata.port_count": "",
		"metadata.default_port_speed_mbps": "",
		"metadata.wifi_standard": "",
		"metadata.ssid_note": "",
		"metadata.cpu_model": "",
		"metadata.memory_gb": "",
		"metadata.storage_summary": "",
		"metadata.primary_nic_speed_mbps": "",
		"metadata.motherboard_vendor": "",
		"metadata.motherboard_model": "",
		"metadata.gpu_detail": "",
		"metadata.memory_detail": "",
		"metadata.storage_detail": "",
		"metadata.nic_detail": "",
		"metadata.chassis_power_detail": "",
		"metadata.planned_agent": "",
		"metadata.connection_type": "",
		"metadata.power_mode": "",
		"metadata.protocol": "http",
		"metadata.entity_id": "",
		"metadata.gateway_name": "",
		"metadata.internal_url": "http://192.168.1.30:8090",
		"metadata.external_url": "",
		"metadata.purchase_date": "",
		"metadata.online_date": "",
		"metadata.warranty_until": "",
		"metadata.owner": "",
	},
	{
		name: "客厅温湿度",
		type: "sensor",
		status: "active",
		location: "客厅",
		vendor: "",
		model: "",
		serial_number: "",
		management_ip: "",
		role: "温湿度传感器",
		notes: "智能家居设备第一阶段可以先手动建档。",
		parent_asset: "",
		"metadata.fixed_ipv4": "",
		"metadata.fixed_ipv6": "",
		"metadata.mac": "",
		"metadata.management_url": "",
		"metadata.support_url": "",
		"metadata.product_url": "",
		"metadata.official_url": "",
		"metadata.down_mbps": "",
		"metadata.up_mbps": "",
		"metadata.public_ipv4": "",
		"metadata.public_ipv6": "",
		"metadata.has_public_ip": "",
		"metadata.port_count": "",
		"metadata.default_port_speed_mbps": "",
		"metadata.wifi_standard": "",
		"metadata.ssid_note": "",
		"metadata.cpu_model": "",
		"metadata.memory_gb": "",
		"metadata.storage_summary": "",
		"metadata.primary_nic_speed_mbps": "",
		"metadata.motherboard_vendor": "",
		"metadata.motherboard_model": "",
		"metadata.gpu_detail": "",
		"metadata.memory_detail": "",
		"metadata.storage_detail": "",
		"metadata.nic_detail": "",
		"metadata.chassis_power_detail": "",
		"metadata.planned_agent": "",
		"metadata.connection_type": "wifi",
		"metadata.power_mode": "battery",
		"metadata.protocol": "zigbee",
		"metadata.entity_id": "",
		"metadata.gateway_name": "",
		"metadata.internal_url": "",
		"metadata.external_url": "",
		"metadata.purchase_date": "",
		"metadata.online_date": "",
		"metadata.warranty_until": "",
		"metadata.owner": "",
	},
]

export function buildAssetImportCsvTemplate() {
	return `\uFEFF${toCsv(ASSET_IMPORT_TEMPLATE_ROWS)}`
}

export function buildAssetImportJsonExample() {
	return JSON.stringify(
		ASSET_IMPORT_TEMPLATE_ROWS.map((row) => {
			const metadata: Record<string, string> = {}
			const asset: Record<string, string | Record<string, string>> = {}
			for (const [key, value] of Object.entries(row)) {
				if (key.startsWith("metadata.")) {
					if (value) metadata[key.slice("metadata.".length)] = value
					continue
				}
				if (value) asset[key] = value
			}
			if (Object.keys(metadata).length > 0) {
				asset.metadata = metadata
			}
			return asset
		}),
		null,
		2
	)
}

function toCsv(rows: Record<string, string>[]) {
	if (rows.length === 0) return ""
	const headers = Object.keys(rows[0])
	const lines = [headers.join(",")]
	for (const row of rows) {
		lines.push(headers.map((header) => escapeCsvValue(row[header])).join(","))
	}
	return lines.join("\r\n")
}

function escapeCsvValue(value: unknown) {
	const text = String(value ?? "")
	if (/[",\r\n]/.test(text)) {
		return `"${text.replace(/"/g, '""')}"`
	}
	return text
}
