import { BoxesIcon } from "lucide-react"
import type { PulseModuleManifest } from "../types"

export const assetCenterModule: PulseModuleManifest = {
	id: "asset-center",
	name: "资产中心",
	description: "统一管理硬件、网络设备、虚拟机、移动设备、网页端点和自定义资产，是监控、拓扑和告警的数据来源。",
	version: "1.0.6",
	category: "资产",
	defaultEnabled: true,
	required: true,
	dependencies: ["foundation"],
	routes: ["/assets", "/assets/:id", "/settings/ai"],
	collections: [
		"system_settings",
		"assets",
		"asset_interfaces",
		"asset_relations",
		"asset_maintenance",
		"asset_attachments",
		"asset_locations",
		"asset_changes",
		"asset_enrichment_reports",
		"asset_enrichment_suggestions",
		"ai_tasks",
		"asset_visuals",
	],
	jobs: ["资产状态汇总", "资产补全报告", "资产全貌图生成"],
	agentCapabilities: [],
	healthChecks: [
		"资产集合",
		"资产关系",
		"资产接口",
		"位置主数据",
		"维护记录",
		"资产附件",
		"变更历史",
		"补全报告",
		"AI 任务",
		"资产视觉",
	],
	sourcePaths: [
		"internal/migrations/assets_collections.go",
		"internal/site/src/components/routes/assets.tsx",
		"internal/site/src/components/routes/settings/ai.tsx",
		"internal/site/src/modules/asset-center",
	],
	icon: BoxesIcon,
}
