FROM --platform=$BUILDPLATFORM golang:alpine AS builder

WORKDIR /app

COPY ../go.mod ../go.sum ./
RUN go mod download

# Copy source files
COPY . ./

# Build
ARG TARGETOS TARGETARCH
ARG AGENT_VERSION=1.0.6-beta.1
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-w -s -X gutenacht.site/pulse.Version=$AGENT_VERSION" -o /agent ./internal/cmd/agent

# --------------------------
# Final image
# Note: must cap_add: [CAP_PERFMON] and mount /dev/dri/ as volume
# --------------------------
FROM alpine:3.23

COPY --from=builder /agent /agent

RUN apk add --no-cache -X https://dl-cdn.alpinelinux.org/alpine/edge/testing dmidecode igt-gpu-tools pciutils smartmontools

# Ensure data persistence across container recreations
VOLUME ["/var/lib/pulse-agent"]

HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \
  CMD ["/agent", "health"]

ENTRYPOINT ["/agent"]
